# Generated by Django 5.2.7 on 2025-11-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('driving_hours', models.FloatField()),
                ('rest_hours', models.FloatField()),
                ('idle_hours', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='roadmap.trip')),
            ],
        ),
    ]
